name: earthdaily
channels:
 - conda-forge
 - defaults
dependencies:
 - numpy
 - python>=3.10
 - gdal>=3.7.0
 - pandas
 - geopandas>=0.11
 - rasterio
 - pystac-client
 - requests
 - matplotlib
 - xarray
 - rioxarray
 - h5netcdf 
 - netcdf4
 - pystac
 - stackstac
 - odc-stac
 - tqdm
 - joblib
 - python-dotenv
