name: Publish release to pypi

on:
  release:
    types: [created]
    
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/earthdaily
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Build package
        run: python setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1