name: pytest-dev

on:
  push:
    branches:
        - dev

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.1-0'
          environment-file: requirements_dev.yml   
          environment-name: earthdaily
          cache-environment: true
          post-cleanup: 'all'
          init-shell: bash
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip install .
      - name: Run tests and coverage
        shell: micromamba-shell {0}
        env:
            EDS_CLIENT_ID: ${{ secrets.EDS_CLIENT_ID }}
            EDS_AUTH_URL: ${{ secrets.EDS_AUTH_URL }}
            EDS_SECRET: ${{ secrets.EDS_SECRET }} 
            EDS_API_URL: ${{ secrets.EDS_API_URL }}
        run: pytest -v tests --cov=earthdaily